CREATE USER core WITH PASSWORD 'core'; 
CREATE DATABASE greenbus3_d;
CREATE DATABASE greenbus3_t;
GRANT ALL PRIVILEGES ON DATABASE greenbus3_d TO core;
GRANT ALL PRIVILEGES ON DATABASE greenbus3_t TO core;

CREATE DATABASE greenbus3_2_t;
GRANT ALL PRIVILEGES ON DATABASE greenbus3_2_t TO core;

